version: '3.8'

services:
  database:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: recipesAppDb
    volumes:
      - recipes-app-db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  server:
    depends_on:
    - database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000

volumes:
  recipes-app-db: